### PR TITLE
Fix missing result message header and improve text visibility

### LINKED ISSUE #181: Fix missing result message and improve text visibility in result header
Result message header was not shown for add/edit/delete commands.

Cause:
- UI only displayed description (used by find), so feedback messages were ignored.

Fix:
- Fallback to feedbackToUser when description is absent
- Adjust text color for better visibility (white on blue)

Result:
- Header message now appears correctly for all commands

### PR DESCRIPTION
**Pull request by Qolivia**
Closes #181

### CODE REVIEW

File: src/main/java/seedu/address/ui/MainWindow.java [hunk 1]
```diff
@@ -197,9 +197,13 @@ private CommandResult executeCommand(String commandText) throws CommandException
      */
     private void displayResult(CommandResult commandResult) {
         if (commandResult.getFoundPersons().isPresent()) {
+            String headerText = commandResult.getDescription().isPresent()
+                    ? commandResult.getDescription().get()
+                    : commandResult.getFeedbackToUser();
+
```
Comment (QR-Phua) [inline src/main/java/seedu/address/ui/MainWindow.java]: ternary operators can be made whole if else blocks for better code quality
